name: rnd_campaign_app

description: Application campagne municipale Nabil Zenasni - Ain El Turck

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # State management
  provider: ^6.1.5+1


  # Backend
  supabase_flutter: ^2.16.0


  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0


  # Authentication
  google_sign_in: ^7.2.0


  # UI
  google_fonts: ^8.2.0


  # Utils
  intl: ^0.20.2


  # Audio
  audioplayers: ^6.8.1
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^22.3.1


dev_dependencies:

  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.8
  googleapis_auth: ^2.3.4
  http: ^1.6.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 256
  image_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background: "#0a1628"
    theme_color: "#0a1628"

flutter_native_splash:
  color: "#0a1628"
  image: "assets/icons/splash.png"
  android: true
  ios: true
  web: false