name: rnd_campaign_app

description: Application campagne municipale Nabil Zenasni - Ain El Turck

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # State management
  provider: ^6.1.5


  # Backend
  supabase_flutter: ^2.10.1


  # Authentication
  google_sign_in: ^7.2.0


  # UI
  google_fonts: ^8.2.0
  cached_network_image: ^3.4.1


  # Maps
  flutter_map: ^8.3.1
  latlong2: ^0.10.1


  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1


  # Images
  image_picker: ^1.1.2
  audioplayers: ^6.8.1


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jfif"

flutter_native_splash:
  color: "#0a1628"
  image: "assets/icons/splash.jfif"
  android: true
  ios: true
  web: false