import 'package:flutter/material.dart';
import 'package:rnd_campaign_app/core/services/translation_service.dart';

class PillarItem {
  final String number;
  final String icon;
  final String title;
  final String subtitle;
  final String tag;
  final List<String> items;
  final Color accentColor;

  PillarItem({
    required this.number,
    required this.icon,
    required this.title,
    required this.subtitle,
    required this.tag,
    required this.items,
    required this.accentColor,
  });
}

class ProgramData {
  static List<PillarItem> getPillars() {
    final lang = TranslationService.currentLang;

    if (lang == 'ar') {
      return [
        PillarItem(
          number: '01',
          icon: '💼',
          title: 'التنمية الاقتصادية والتجارة والتوظيف',
          subtitle: 'أولويتنا هي تحويل عين الترك إلى بلدية تُنتج الثروة.',
          tag: 'التنمية الاقتصادية',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "فتح طريق ثانٍ يربط طرفي البلدية لتخفيف الازدحام المروري.",
            "إنجاز التوصيلات اللازمة على هذا الطريق الموجود بالفعل.",
            "إنشاء ممر اقتصادي جديد يشجع على استقرار المتاجر والمحلات التجارية الجديدة.",
            "تعزيز قيمة الأراضي والمساكن والإقامات الواقعة على طول هذا الطريق الجديد.",
            "خلق فرص عمل مباشرة وغير مباشرة.",
            "إنشاء سوق يومي في تروفيل (قيد الدراسة).",
            "إنشاء سوق أسبوعي للمركبات عند مدخل أو مخرج البلدية.",
            "تركيب أكشاك تجارية متناسقة وفق هندسة معمارية على الطراز الكاليفورني.",
            "إنشاء قاعدة بيانات تسرد جميع المتاجر والمؤسسات والحرفيين والمهن الحرة والجمعيات والأندية والخدمات بالبلدية من أجل تسهيل التبادلات الاقتصادية وللوصول المواطنين إلى الخدمات.",
            "تنظيم لقاءات دورية بين المؤسسات والتجار والمستثمرين والأندية والجمعيات من أجل تطوير الرعاية والشراكات والمشاريع المشتركة.",
            "تشجيع المؤسسات الحاصلة على صفقات عمومية، في احترام للتنظيم، على المساهمة في حل مشكلتين ذات اهتمام بلدي في إطار مسؤوليتها الاجتماعية.",
          ],
        ),
        PillarItem(
          number: '02',
          icon: '🚗',
          title: 'التنقل والسير والمواصلات',
          subtitle: 'التنقل ضروري للتنمية الاقتصادية.',
          tag: 'التنقل',
          accentColor: const Color(0xFFff006e),
          items: const [
            "فتح الطريق الثاني لتسهيل حركة المرور بشكل دائم.",
            "إنشاء خطوط جديدة للنقل العمومي.",
            "إنشاء خطوط جديدة للتاكسي تخدم الأحياء النائية.",
            "خدمة أفضل للأحياء حتى لا يضطر المواطنون لقطع مسافات طويلة سيراً على الأقدام للوصول إلى الطريق الوطني.",
            "إدارة أفضل لتدفقات المرور خلال الموسم الصيفي.",
            "بناء 6 جسور لتحويل المرور من الطريق نحو الأندلس وتمكين الوصول إلى مدينة عين الترك بسهولة، وتجنب الاختناقات المرورية أو الازدحام.",
            "إنشاء محطات للنقل العمومي بالقرب من التجمعات السكنية تروفيل، بويسفيل، بنسمير، بالقرب من مداخل الطريق السريع وكاب فالكون، ليدون.",
          ],
        ),
        PillarItem(
          number: '03',
          icon: '🏖️',
          title: 'السياحة والشواطئ والجاذبية',
          subtitle: 'يجب أن تصبح عين الترك مرجعاً وطنياً بين المنتجعات البحرية.',
          tag: 'السياحة',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "مداخل شاطئ مصممة لتدوم بفضل تصنيع البلدية لقوالبها الخاصة من جدران على الطراز العثماني.",
            "استخدام مونة ملونة أكثر مقاومة لرطوبة البحر.",
            "جسور ومداخل خشبية مستوحاة من الطراز الكاليفورني.",
            "إنشاء فرق دائمة لتنظيف الشواطئ.",
            "تنظيم حملات توعية.",
            "تركيب لوحات حديثة تذكر بقواعد النظافة والأمن وحماية البيئة.",
            "تطوير الأنشطة البحرية.",
            "دعم الأندية والجمعيات المنظمة للفعاليات الرياضية والثقافية والبحرية.",
            "منصة رقمية تجمع جميع المعلومات المفيدة للمواطنين والسياح.",
          ],
        ),
        PillarItem(
          number: '04',
          icon: '🌳',
          title: 'البيئة والمساحات الخضراء وجودة الحياة',
          subtitle: 'نريد بلدية أكثر خضرة وأكثر متعة وأكثر استدامة.',
          tag: 'البيئة',
          accentColor: const Color(0xFF00A651),
          items: const [
            "إنشاء مشتل بلدي.",
            "زراعة 10,000 شجرة متأقلمة مع المناخ المحلي وسريعة النمو.",
            "حماية صارمة للتراث الشجري.",
            "منع قطع الأشجار أو الإضرار بها خارج الأحكام المنصوص عليها في القانون.",
            "تصنيع محلي لمناطق اللعب المخصصة للحدائق البلدية لتقليل التكاليف وتسريع التجديدات وتكثيف أماكن الترفيه.",
          ],
        ),
        PillarItem(
          number: '05',
          icon: '📱',
          title: 'بلدية رقمية وإدارة حديثة',
          subtitle: 'يجب أن يتمكن المواطن من التواصل بسهولة مع بلديته.',
          tag: 'الرقمية',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "الإبلاغ عن المشاكل مع تحديد الموقع الجغرافي؛",
            "الإبلاغ عن الحوادث؛",
            "تحديد النقاط السوداء؛",
            "متابعة معالجة الطلبات في الوقت الفعلي؛",
            "الاطلاع على آجال التدخل؛",
            "التواصل المباشر مع العمدة أو الخدمات البلدية؛",
            "إرسال الاقتراحات والمقترحات؛",
            "متابعة إنجازات البلدية.",
            "تعزيز الوكالات خلال فترات الازدحام الشديد؛",
            "تكييف الأعداد حسب الحاجات؛",
            "إنشاء خلية مراقبة؛",
            "إنشاء خلية أزمات؛",
            "إمكانية الإبلاغ عن التأخيرات أو الاختلالات عبر التطبيق مع متابعة الردود.",
          ],
        ),
        PillarItem(
          number: '06',
          icon: '⚖️',
          title: 'الحوكمة والشفافية والمشاركة المواطنة',
          subtitle: 'الثقة تُبنى بالشفافية.',
          tag: 'الحوكمة',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "نشر برنامجنا كاملاً؛",
            "نشر تقرير مفصل بالإنجازات في نهاية كل سنة أو كل ولاية؛",
            "تنظيم لقاءات شهرية مفتوحة للمواطنين؛",
            "جمع مقترحات المواطنين عبر التطبيق البلدي؛",
            "إشراك السكان في القرارات المتعلقة ببلديتهم.",
          ],
        ),
      ];
    } else if (lang == 'en') {
      return [
        PillarItem(
          number: '01',
          icon: '💼',
          title: 'Economic Development, Commerce and Employment',
          subtitle: 'Our priority is to transform Ain El Turck into a wealth-generating communality.',
          tag: 'Economic Development',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "Opening a second road connecting the two ends of the communality to ease traffic flow.",
            "Carrying out the necessary connections on this already existing road.",
            "Creating a new economic corridor promoting the establishment of businesses and new commercial premises.",
            "Enhancing the value of land, homes and residences located along this new road.",
            "Creating direct and indirect jobs.",
            "Creating a daily market in Trouville (under study).",
            "Creating a weekly vehicle market at the entrance or exit of the communality.",
            "Installing harmonized commercial kiosks according to California-style architecture.",
            "Creating a database listing all businesses, companies, craftsmen, liberal professions, associations, clubs and services of the communality to facilitate economic exchanges and citizen access to services.",
            "Organizing regular meetings between companies, traders, investors, clubs and associations to develop sponsorship, partnerships and joint projects.",
            "Encouraging, in compliance with regulations, public contract holders to contribute to solving two problems of communal interest as part of their social responsibility.",
          ],
        ),
        PillarItem(
          number: '02',
          icon: '🚗',
          title: 'Mobility, Traffic and Transport',
          subtitle: 'Mobility is essential for economic development.',
          tag: 'Mobility',
          accentColor: const Color(0xFFff006e),
          items: const [
            "Opening the second road to ease traffic flow in the long term.",
            "Creating new public transport lines.",
            "Creating new taxi lines serving remote neighborhoods.",
            "Better service to neighborhoods so that citizens no longer have to walk long distances to reach the national road.",
            "Better management of traffic flows during the summer season.",
            "Building 6 bridges for the bypass from the road to the Andalouses to allow easy access and avoid traffic jams.",
            "Creating public transport stations near the agglomerations Trouville, Bouisseville, Bensmir, near highway access, Cap Falcon, and Les Dunes.",
          ],
        ),
        PillarItem(
          number: '03',
          icon: '🏖️',
          title: 'Tourism, Beaches and Attractiveness',
          subtitle: 'Ain El Turck must become a national reference among seaside resorts.',
          tag: 'Tourism',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "Beach access designed to last thanks to the APC manufacturing its own Ottoman-style wall molds.",
            "Using tinted mortars more resistant to marine humidity.",
            "Wooden footbridges and beach access inspired by California-style.",
            "Creating permanent beach cleaning squads.",
            "Implementing awareness raising activities.",
            "Installing modern signs reminding of cleanliness, safety and environmental protection rules.",
            "Developing water activities.",
            "Supporting clubs and associations organizing sports, cultural and maritime events.",
            "A digital platform gathering all useful information for citizens and tourists.",
          ],
        ),
        PillarItem(
          number: '04',
          icon: '🌳',
          title: 'Environment, Green Spaces and Quality of Life',
          subtitle: 'We want a greener, more pleasant and more sustainable communality.',
          tag: 'Environment',
          accentColor: const Color(0xFF00A651),
          items: const [
            "Creating a communal nursery.",
            "Planting 10,000 trees adapted to the local climate and fast-growing.",
            "Strict protection of the tree heritage.",
            "Banning tree cutting or damage outside legal provisions.",
            "Local manufacturing of playgrounds for municipal parks to reduce costs, speed up renovations and multiply leisure spaces.",
          ],
        ),
        PillarItem(
          number: '05',
          icon: '📱',
          title: 'A Digital Communality and Modern Administration',
          subtitle: 'The citizen must be able to communicate easily with their communality.',
          tag: 'Digital',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "reporting issues with geolocation;",
            "reporting accidents;",
            "identifying black spots;",
            "tracking requests processing in real-time;",
            "viewing intervention response times;",
            "directly contacting the mayor or municipal services;",
            "sending suggestions and proposals;",
            "tracking the achievements of the communality.",
            "reinforcing counters during peak traffic periods;",
            "adapting staff size according to needs;",
            "creating a monitoring cell;",
            "creating a crisis cell;",
            "ability to report delays or dysfunctions via the application with follow-up responses.",
          ],
        ),
        PillarItem(
          number: '06',
          icon: '⚖️',
          title: 'Governance, Transparency and Citizen Participation',
          subtitle: 'Trust is built through transparency.',
          tag: 'Governance',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "publishing our entire program;",
            "publishing a detailed balance sheet of achievements at the end of each year or each term;",
            "organizing monthly town hall meetings open to all;",
            "collecting citizens' proposals via the communal app;",
            "involving residents in decisions concerning their communality.",
          ],
        ),
      ];
    } else {
      // Default: 'fr'
      return [
        PillarItem(
          number: '01',
          icon: '💼',
          title: 'Développement économique, commerce et emploi',
          subtitle: 'Notre priorité est de transformer Aïn El Turck en une commune créatrice de richesse.',
          tag: 'Développement Économique',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "L'ouverture d'une deuxième route reliant les deux extrémités de la commune afin de désengorger la circulation.",
            "La réalisation des raccordements nécessaires sur cette route déjà existante.",
            "La création d'un nouveau corridor économique favorisant l'implantation de commerces et de nouveaux locaux commerciaux.",
            "La valorisation des terrains, habitations et résidences situés le long de cette nouvelle voie.",
            "La création d'emplois directs et indirects.",
            "La création d'un marché quotidien à Trouville (à l'étude).",
            "La création d'un marché hebdomadaire de véhicules à l'entrée ou à la sortie de la commune.",
            "L'installation de kiosques commerciaux harmonisés selon une architecture de style californien.",
            "La création d'une base de données recensant tous les commerces, entreprises, artisans, professions libérales, associations, clubs et services de la commune afin de faciliter les échanges économiques et l'accès des citoyens aux services.",
            "L'organisation de rencontres régulières entre entreprises, commerçants, investisseurs, clubs et associations afin de développer le sponsoring, les partenariats et les projets communs.",
            "Encourager, dans le respect de la réglementation, les entreprises titulaires de marchés publics à contribuer à la résolution de deux problématiques d'intérêt communal dans le cadre de leur responsabilité sociétale.",
          ],
        ),
        PillarItem(
          number: '02',
          icon: '🚗',
          title: 'Mobilité, circulation et transports',
          subtitle: 'La mobilité est indispensable au développement économique.',
          tag: 'Mobilité',
          accentColor: const Color(0xFFff006e),
          items: const [
            "L'ouverture de la deuxième route afin de fluidifier durablement la circulation.",
            "La création de nouvelles lignes de transport en commun.",
            "La création de nouvelles lignes de taxis desservant les quartiers éloignés.",
            "Une meilleure desserte des quartiers afin que les citoyens n'aient plus à parcourir de longues distances à pied pour rejoindre la route nationale.",
            "Une meilleure gestion des flux routiers pendant la saison estivale.",
            "Bâtir 6 ponts pour la déviation depuis la route vers les Andalouses et permettre l'accès à la ville d'Aïn El Turck facilement, d'éviter les embouteillages ou encombrements.",
            "Création de stations de transport en commun près des agglomérations Trouville, Bouisseville, Bensmir, près des accès de l'autoroute et Cap Falcon, Les Dunes.",
          ],
        ),
        PillarItem(
          number: '03',
          icon: '🏖️',
          title: 'Tourisme, plages et attractivité',
          subtitle: 'Aïn El Turck doit de venir une référence nationale parmi les stations balnéaires.',
          tag: 'Tourisme',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "Des accès aux plages conçus pour durer grâce à la fabrication par l'APC de ses propres moules de murs de style architecture osmanienne.",
            "L'utilisation de mortiers teintés plus résistants à l'humidité marine.",
            "Des passerelles et accès en bois inspirés du style californien.",
            "La création de brigades permanentes de nettoyage des plages.",
            "La mise en place d'animations de sensibilisation.",
            "L'installation de panneaux modernes rappelant les règles de propreté, de sécurité et de protection de l'environnement.",
            "Le développement des activités nautiques.",
            "Le soutien aux clubs et associations organisant des événements sportifs, culturels et maritimes.",
            "Une plateforme numérique regroupant toutes les informations utiles aux citoyens et aux touristes.",
          ],
        ),
        PillarItem(
          number: '04',
          icon: '🌳',
          title: 'Environnement, espaces verts et cadre de vie',
          subtitle: 'Nous voulons une commune plus verte, plus agréable et plus durable.',
          tag: 'Environnement',
          accentColor: const Color(0xFF00A651),
          items: const [
            "La création d'une pépinière communale.",
            "La plantation de 10 000 arbres adaptés au climat local et à croissance rapide.",
            "La protection stricte du patrimoine arboricole.",
            "L'interdiction de couper les arbres ou de leur porter atteinte en dehors des dispositions prévues par la loi.",
            "La fabrication locale des aires de jeux destinées aux parcs municipaux afin de réduire les coûts, accélérer les rénovations et multiplier les espaces de loisirs.",
          ],
        ),
        PillarItem(
          number: '05',
          icon: '📱',
          title: 'Une commune numérique et une administration moderne',
          subtitle: 'Le citoyen doit pouvoir communiquer facilement avec sa commune.',
          tag: 'Numérique',
          accentColor: const Color(0xFF00d4ff),
          items: const [
            "de signaler les problèmes avec géolocalisation ;",
            "de signaler les accidents ;",
            "d'identifier les points noirs ;",
            "de suivre en temps réel le traitement des demandes ;",
            "de consulter les délais d'intervention ;",
            "de contacter directement le maire ou les services municipaux ;",
            "d'envoyer des suggestions et propositions ;",
            "de suivre les réalisations de la commune.",
            "renforcement des guichets lors des périodes de forte affluence ;",
            "adaptation des effectifs selon les besoins ;",
            "création d'une cellule de veille ;",
            "création d'une cellule de crise ;",
            "possibilité de signaler les retards ou dysfonctionnements via l'application avec suivi des réponses.",
          ],
        ),
        PillarItem(
          number: '06',
          icon: '⚖️',
          title: 'Gouvernance, transparence et participation citoyenne',
          subtitle: 'La confiance se construit par la transparence.',
          tag: 'Gouvernance',
          accentColor: const Color(0xFFd4af37),
          items: const [
            "publier l'intégralité de notre programme ;",
            "publier un bilan détaillé des réalisations à la fin de chaque année ou de chaque mandat ;",
            "organiser des rencontres citoyennes mensuelles ouvertes à tous ;",
            "recueillir les propositions des citoyens via l'application communale ;",
            "associer les habitants aux décisions concernant leur commune.",
          ],
        ),
      ];
    }
  }
}
