// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJrRN3nkLa55XBMctnjHJICyAc6-AJOk',
    appId: '1:557594232565:web:cf11e2a0948b2e470a27bc',
    messagingSenderId: '557594232565',
    projectId: 'rnd-aet',
    authDomain: 'rnd-aet.firebaseapp.com',
    storageBucket: 'rnd-aet.firebasestorage.app',
    measurementId: 'G-K1RJ046Y4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1R8Z5_7xZhhNS4xXxw-Ju1Zm_YEPueRo',
    appId: '1:557594232565:android:467fb38aaada09090a27bc',
    messagingSenderId: '557594232565',
    projectId: 'rnd-aet',
    storageBucket: 'rnd-aet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUThK2-mg4pUEey8lOnHAvkIcmgFgq7dk',
    appId: '1:557594232565:ios:ca616f7b5be97e1e0a27bc',
    messagingSenderId: '557594232565',
    projectId: 'rnd-aet',
    storageBucket: 'rnd-aet.firebasestorage.app',
    iosBundleId: 'com.rnd.dz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUThK2-mg4pUEey8lOnHAvkIcmgFgq7dk',
    appId: '1:557594232565:ios:ca616f7b5be97e1e0a27bc',
    messagingSenderId: '557594232565',
    projectId: 'rnd-aet',
    storageBucket: 'rnd-aet.firebasestorage.app',
    iosBundleId: 'com.rnd.dz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJrRN3nkLa55XBMctnjHJICyAc6-AJOk',
    appId: '1:557594232565:web:b416c7f29a2e90210a27bc',
    messagingSenderId: '557594232565',
    projectId: 'rnd-aet',
    authDomain: 'rnd-aet.firebaseapp.com',
    storageBucket: 'rnd-aet.firebasestorage.app',
    measurementId: 'G-YYGTZLPE91',
  );
}
